package alina.com.rms.util;

/**
 * Created by HP on 02-01-2018.
 */

public enum CallType {
    POST_LOGIN,GET_OHE,GET_TARGET_VALUE,SUBMITTED_VALUE,RECOVERY_PASSWORD,GET_SP_TARGET,GET_SP_TARGET_VALUE,
    GET_TSS_TARGET,GET_SSP_TARGET_VALUE,GET_TSS_TARGET_VALUE,SAVE_SP_TARGET_VALUE,SAVE_SSP_TARGET_VALUE,
    SAVE_TSS_TARGET_VALUE,GET_HQ_LIST,ADD_HEAD_QUATER,UPDATE_HEAD_QUATER,DELETE_HEAD_QUATER,GET_SUPER_ADMIN_USER_LIST
    ,DELETE_SUPER_ADMIN_USER,UPDATE_SUPER_ADMIN_USER,ADD_SUPER_ADMIN_USER,GET_GROUP_USER,GET_SECTION_LIST,ADD_SECTION,
    GET_TARGET_VALUE_HEADQUATER,SET_TARGET_VALUE,GET_MASTER_LIST,DELETE_MASTER,GET_TSS,GET_SP,GET_SSP,GET_ORGNAIZATION_LIST,
    GET_STATE_LIST,GET_ZONE_LIST,SET_RKM,GET_DVISION_LIST,GET_PUBLIC_MODULE_LIST,DELETE_MODULE,UPDATE_RKM,GET_RKM,GET_PROJECT_LIST
    ,GET_CRS_LIST,GET_FOUNDATION_LIST,SAVE_FOUNDATION_ITEM,VIEW_FOUNDATION_MODEL,UPDATE_FOUNDATION,EDIT_FOUNDATION_DATA,
    VIEW_MASTERICTION_MODEL,GET_STATION_LIST,GET_ACTIVITY_LIST,GET_NAME_LIST

}
